 var digito_1 = document.getElementById("digito_1")
 var digito_2 = document.getElementById("digito_2")
 var digito_3 = document.getElementById("digito_3")
 var digito_4 = document.getElementById("digito_4")
 var digito_5 = document.getElementById("digito_5")
 var digito_6 = document.getElementById("digito_6")
 var digito_7 = document.getElementById("digito_7")
 var digito_8 = document.getElementById("digito_8")
 var digito_9 = document.getElementById("digito_9")
 var digito_0 = document.getElementById("digito_0")
 var negativo = document.getElementById("negativo")
 var virgula = document.getElementById("virgula")
 var operador_soma = document.getElementById("operador_soma")
 var operador_subtracao = document.getElementById("operador_subtracao" )
 var operador_divisao = document.getElementById("operador_divisao")
 var operador_multiplicacao = document.getElementById("operador_multiplicacao")
 var operador_porcentagem = document.getElementById("operador_porcentagem")
 var operador_potenciacao = document.getElementById("operador_potenciacao")
 var operador_radiciacao = document.getElementById("operador_radiciacao")
 var operador_fracao= document.getElementById("operador_fracao")
 var backspace = document.getElementById("backspace")
 var limpa_telaC = document.getElementById("limpa_telaC")
 var limpa_telaCE = document.getElementById("limpa_telaCE")
 var botao_resultado = document.getElementById("botao_resultado")
 

